== Задание ==


=== Задача №1 ===

Компонент функциональности генерации заданного количества случайных уникальных чисел. 

Пример:

Если на входе n = 5, то на выходе функции ответ может быть например такой:

[,py]
....
[2, 7, 10, 3, 4]
....

==== Требуется: ====
1. Реализовать описанную функциональность в виде функции:
+
[,py]
....
from typing import List

def generateUniqueNumbers(n: int) -> List[int]:
    # TODO
....
+
2. Обеспечить максимально быстрое выполнение выбором оптимального алгоритма.
3. Из внешних пакетов можно пользоваться только стандартной библиотекой языка.
4. Оценить вычислительную сложность алгоритма реализации (можно в нотации O).
5. Оценить сложность алгоритма реализации по расходу памяти (можно в нотации O).


=== Задача №2 ===

База данных PostgreSQL содержит информацию о покупках в платформе. Она хранит для идентификатор покупателя, идентификатор товара, кол-во купленного товара, дату и время покупки.

==== Требуется: ====

1. Написать SQL-запрос для создания таблицы `purchase` из описания задачи. Помимо указанной информации о покупках в таблице также должен хранится целочисленный идентификатор покупки, который может назначаться пользователю при его занесении в таблицу.

2. Для поиска покупки по идентификатору пользователя обеспечить наличие соответствующего индекса.

3. Для поиска покупки во временном диапазоне (например с 2022-01-30 15:00 2022-02-28 15:00) обеспечить наличие соответствующего индекса.

4. Написать SQL-запрос для поиска покупок, которые совершил пользователь с идентификатором `127`.

5. Написать SQL-запрос для поиска покупок, совершенных с 2022-01-30 15:00 2022-02-28 15:00.

6. Написать SQL-запрос для поиска покупок продукта с идентификатором `246235231`

7. В какой-то момент времени потребовалось также хранить информацию о сумме покупки в евро. Необходимо написать SQL-запрос на добавление поля `cost` в таблицу `purchase`.